### ISSUE TITLE
Mosquitto broker and clients

### ISSUE THREAD

**Issue by peno64** [peno64/test#7]
@pch3

Hi,

In the past you had a repo called kodi.mqtt.broker
This is now deleted. I guess because the addon was outdated.

I am especially interested in the bin and lib folders under service.mosquitto/ because I could just copy these folders to my raspberry 3 and 4 running under libreelec and as such I could send mqtt messages.

This also worked on raspberry pi 5 with libreelec until they recently switched to 64 bit.

My question to you is, where did you find those binaries and libraries? I can't seem to find them. Maybe there are now also 64 binaries available where you found them so you could really help me here.

Thank  you

**Comment by pch3** [comment]
Hi
That was very long time ago :)
If I remember correctly I took mosquitto binnaries from rasbian and build the rest myself. I may be wrong though. Sorry, I really don't remember.

Cheers
Piotr

**Comment by peno64** [comment]
@pch3 

Thank you.
It was a long shot.
I am now also at the point of compiling the binaries myself.
